_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 17
                - 23
                - 55
            "4": 3.11.3
            "5": 0.19.8
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.8
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: ReLU
batch_size:
    value: 64
beta:
    value: 0.5
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
epochs:
    value: 10
epsilon:
    value: 1e-08
hidden_size:
    value: 128
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
momentum:
    value: 0.9
num_layers:
    value: 2
optimizer:
    value: adam
wandb_entity:
    value: pankuu21-indian-institute-of-technology-madras
wandb_project:
    value: DA6401_Assignment1
weight_decay:
    value: 0.0001
weight_init:
    value: Xavier
